# -*- coding: utf-8 -*-
"""IDSC 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rkygti5xI7HtLQkpq84rAW90QA7aK6RK

# PROGRAM AWAL
"""

# path dataset citra /content/drive/MyDrive/Competition/IDSC 2026/Dataset/hillel-yaffe-glaucoma-dataset/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0/Images
# path dataset tabular /content/drive/MyDrive/Competition/IDSC 2026/Dataset/hillel-yaffe-glaucoma-dataset/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0/Labels.csv

import os
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.model_selection import GroupShuffleSplit
from PIL import Image
import matplotlib.pyplot as plt

# ======================================================
# 1. KONFIGURASI PATH
# ======================================================
BASE_PATH = '/content/drive/MyDrive/Competition/IDSC 2026/Dataset/hillel-yaffe-glaucoma-dataset/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0'
IMAGE_DIR = os.path.join(BASE_PATH, 'Images')
CSV_PATH = os.path.join(BASE_PATH, 'Labels.csv')

# ======================================================
# 2. AUTO-MAPPER & SPLITTER (TAHAP 1 AMAN DARI ERROR)
# ======================================================
def prepare_and_split(csv_path):
    print("--- Membaca Metadata & Deteksi Kolom ---")
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip() # Bersihkan spasi tersembunyi

    cols = df.columns.str.lower()

    # Deteksi dinamis 4 kolom utama
    try:
        col_img = df.columns[['image' in c or 'file' in c or 'name' in c for c in cols]][0]
        col_pat = df.columns[['patient' in c or 'id' in c for c in cols]][0]
        col_lab = df.columns[['diagnosis' in c or 'label' in c or 'gon' in c for c in cols]][0]
        col_qty = df.columns[['quality' in c or 'score' in c for c in cols]][0]
    except IndexError:
        print(f"❌ ERROR: Tidak dapat memetakan kolom. Kolom yang tersedia: {list(df.columns)}")
        raise

    print(f"✅ Pemetaan Kolom Berhasil:")
    print(f"   - Gambar  : '{col_img}'")
    print(f"   - Pasien  : '{col_pat}'")
    print(f"   - Label   : '{col_lab}'")
    print(f"   - Kualitas: '{col_qty}'")

    # Patient-Level Split (73% Train, 13.5% Val, 13.5% Test)
    # Split 1: Ambil 13.5% untuk Test (menyisakan 86.5% untuk Train+Val)
    gss_test = GroupShuffleSplit(n_splits=1, test_size=0.135, random_state=42)
    train_val_idx, test_idx = next(gss_test.split(df, groups=df[col_pat]))

    df_train_val = df.iloc[train_val_idx].copy()
    df_test = df.iloc[test_idx].copy()

    # Split 2: Bagi sisa 86.5% agar Val mendapat porsi 13.5% dari total data (13.5 / 86.5 = 0.156)
    gss_val = GroupShuffleSplit(n_splits=1, test_size=0.156, random_state=42)
    train_idx, val_idx = next(gss_val.split(df_train_val, groups=df_train_val[col_pat]))

    df_train = df_train_val.iloc[train_idx].copy()
    df_val = df_train_val.iloc[val_idx].copy()

    print(f"\n✅ Data Terbagi! Train: {len(df_train)}, Val: {len(df_val)}, Test: {len(df_test)}")

    # Kembalikan dataframe dan dictionary nama kolom agar Dataset Class tidak error
    col_dict = {'img': col_img, 'pat': col_pat, 'lab': col_lab, 'qty': col_qty}
    return df_train, df_val, df_test, col_dict

# ======================================================
# 3. CLASS DATASET YANG FLEKSIBEL (FIXED LABEL CONVERSION)
# ======================================================
class HYGDDataset(Dataset):
    def __init__(self, dataframe, root_dir, col_dict, transform=None):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.cols = col_dict
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # 1. Load Nama Gambar & Fisik Gambar
        img_name = str(self.df.loc[idx, self.cols['img']])
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_name += '.jpg'

        img_path = os.path.join(self.root_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        # 2. Konversi Label Teks ('GON+' / 'GON-') ke Angka (1 / 0)
        raw_label = str(self.df.loc[idx, self.cols['lab']]).strip().upper()
        if raw_label == 'GON+':
            label = 1
        elif raw_label == 'GON-':
            label = 0
        else:
            # Jaga-jaga jika ternyata isinya sudah berbentuk angka 1 atau 0 dari CSV-nya
            try:
                label = int(float(raw_label))
            except ValueError:
                label = 0 # Default fallback

        # 3. Normalisasi Quality Score (0 - 1)
        quality = float(self.df.loc[idx, self.cols['qty']]) / 10.0

        if self.transform:
            image = self.transform(image)

        return {
            'image': image,
            'label': torch.tensor(label, dtype=torch.long),
            'quality': torch.tensor(quality, dtype=torch.float32)
        }

# ======================================================
# 4. EKSEKUSI & TEST TAHAP 1
# ======================================================
if __name__ == "__main__":
    try:
        # 1. Jalankan Split & Mapper
        df_train, df_val, df_test, cols = prepare_and_split(CSV_PATH)

        # 2. Setup Transform & Loader
        test_transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
        ])

        train_ds = HYGDDataset(df_train, IMAGE_DIR, cols, transform=test_transform)
        train_loader = DataLoader(train_ds, batch_size=4, shuffle=True)

        # 3. Ambil 1 batch untuk verifikasi akhir
        batch = next(iter(train_loader))
        print("\n--- Verifikasi Batch Gambar ---")
        print(f"Shape Tensor Gambar: {batch['image'].shape}")
        print(f"Label GON+/GON-    : {batch['label']}")
        print(f"Skor Kualitas (0-1): {batch['quality']}")
        print("✅ TAHAP 1 SELESAI DAN AMAN DARI ERROR!")

    except FileNotFoundError:
        print("\n❌ File tidak ditemukan. Pastikan Google Drive sudah di-mount:")
        print("from google.colab import drive\ndrive.mount('/content/drive')")
    except Exception as e:
        print(f"\n❌ Terjadi Error Lain: {e}")

import torchvision.transforms as T
import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import os
import matplotlib.pyplot as plt
import numpy as np

# ======================================================
# 1. DEFINISI PIPELINE TRANSFORMASI (TAHAP 2)
# ======================================================
IMG_SIZE = 224 # Sesuai diagram: Resize ke 224x224 (atau 384x384)

# A. Transformasi Standar (Untuk Val & Test Set)
val_test_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # Standar ImageNet
])

# B. Transformasi Dasar (Untuk Train Set kelas mayoritas GON+)
train_base_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5), # Augmentasi ringan
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# C. Transformasi Agresif (Khusus Train Set kelas minoritas GON-)
train_aggressive_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5),
    T.RandomVerticalFlip(p=0.5),
    T.RandomRotation(degrees=30), # Putar acak hingga 30 derajat
    T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05), # Ubah pencahayaan
    T.RandomAffine(degrees=0, translate=(0.1, 0.1)), # Geser gambar sedikit
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# ======================================================
# 2. UPDATE CLASS DATASET (Conditional Augmentation)
# ======================================================
class HYGDDatasetV2(Dataset):
    def __init__(self, dataframe, root_dir, col_dict, is_train=False):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.cols = col_dict
        self.is_train = is_train # Penanda apakah ini data training

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # 1. Load Gambar
        img_name = str(self.df.loc[idx, self.cols['img']])
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_name += '.jpg'
        img_path = os.path.join(self.root_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        # 2. Load Label & Quality Score
        raw_label = str(self.df.loc[idx, self.cols['lab']]).strip().upper()
        label = 1 if raw_label == 'GON+' else (0 if raw_label == 'GON-' else int(float(raw_label)))
        quality = float(self.df.loc[idx, self.cols['qty']]) / 10.0

        # 3. Terapkan Transformasi Bersyarat (Inti dari Tahap 2)
        if self.is_train:
            if label == 0: # Minoritas GON- (27%)
                image = train_aggressive_transform(image)
            else:          # Mayoritas GON+ (73%)
                image = train_base_transform(image)
        else:
            # Jika Val / Test, selalu gunakan transformasi standar
            image = val_test_transform(image)

        return {
            'image': image,
            'label': torch.tensor(label, dtype=torch.long),
            'quality': torch.tensor(quality, dtype=torch.float32)
        }

# ======================================================
# 3. INISIALISASI DATALOADER FINAL TAHAP 2
# ======================================================
if __name__ == "__main__":
    # Menggunakan df_train, df_val, df_test, dan cols dari Tahap 1 sebelumnya

    # Buat Dataset (Perhatikan parameter is_train)
    train_ds = HYGDDatasetV2(df_train, IMAGE_DIR, cols, is_train=True)
    val_ds = HYGDDatasetV2(df_val, IMAGE_DIR, cols, is_train=False)
    test_ds = HYGDDatasetV2(df_test, IMAGE_DIR, cols, is_train=False)

    # Buat DataLoader
    train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_ds, batch_size=16, shuffle=False, num_workers=2)

    print("✅ TAHAP 2 SELESAI: Pipeline Preprocessing & Augmentasi Agresif berhasil dibuat!")
    print(f"Jumlah Batch per Epoch (Train): {len(train_loader)}")

!pip install timm

import torch
import torch.nn as nn
import timm

# ======================================================
# ARSITEKTUR TAHAP 3: QUALITY-AWARE SWIN TRANSFORMER
# ======================================================
class QualityAwareSwin(nn.Module):
    def __init__(self, model_name='swin_base_patch4_window7_224', pretrained=True, num_classes=2):
        super(QualityAwareSwin, self).__init__()

        # ---------------------------------------------------
        # 1. CABANG VISUAL (SWIN TRANSFORMER BACKBONE)
        # ---------------------------------------------------
        # num_classes=0 membuang layer klasifikasi asli bawaan ImageNet
        # Ini menyisakan kita dengan 'Visual Feature Vector' (Pooling Layer)
        self.swin = timm.create_model(model_name, pretrained=pretrained, num_classes=0)

        # Mengambil dimensi output dari Swin (Biasanya 1024 untuk swin_base)
        swin_out_features = self.swin.num_features

        # ---------------------------------------------------
        # 2. CABANG KUALITAS (DENSE LAYER / MLP)
        # ---------------------------------------------------
        # Input: 1 nilai (Skor Kualitas 0-1)
        # Output: Vektor representasi kualitas (misal: 16 dimensi)
        self.quality_mlp = nn.Sequential(
            nn.Linear(1, 16),
            nn.GELU(), # GELU seringkali lebih baik dari ReLU di arsitektur Transformer
            nn.Linear(16, 16),
            nn.GELU()
        )

        # ---------------------------------------------------
        # 3. FUSION & FULLY CONNECTED CLASSIFIER
        # ---------------------------------------------------
        # Input: 1024 (Visual) + 16 (Quality) = 1040 dimensi
        self.classifier = nn.Sequential(
            nn.Linear(swin_out_features + 16, 512),
            nn.GELU(),
            nn.Dropout(0.3), # Mencegah overfitting
            nn.Linear(512, num_classes) # Output: 2 node (GON- dan GON+)
        )

    def forward(self, image, quality_score):
        # A. Ekstraksi Fitur Spasial
        visual_features = self.swin(image) # Shape: [Batch, 1024]

        # B. Ekstraksi Fitur Kualitas
        # Pastikan skor kualitas punya dimensi [Batch, 1] bukan cuma [Batch]
        if quality_score.dim() == 1:
            quality_score = quality_score.unsqueeze(1)

        quality_features = self.quality_mlp(quality_score) # Shape: [Batch, 16]

        # C. Fusion / Concatenation
        # Menggabungkan kedua vektor secara horizontal (dim=1)
        fused_features = torch.cat((visual_features, quality_features), dim=1) # Shape: [Batch, 1040]

        # D. Prediksi Akhir
        output = self.classifier(fused_features) # Shape: [Batch, 2]

        return output

# ======================================================
# UJI COBA ARSITEKTUR (SIMULASI FORWARD PASS)
# ======================================================
if __name__ == "__main__":
    print("--- Inisialisasi Model Quality-Aware Swin ---")
    # Gunakan versi 'tiny' atau 'small' dulu jika memori GPU terbatas,
    # tapi kita pakai 'base' sesuai standar umum
    model = QualityAwareSwin(model_name='swin_base_patch4_window7_224', pretrained=True)

    # Ambil 1 batch dari train_loader (Tahap 2) yang sudah kita buat sebelumnya
    # Jika train_loader belum jalan, kita pakai tensor dummy untuk tes:
    print("\nMembuat Tensor Dummy untuk simulasi Batch Size = 4...")
    dummy_images = torch.randn(4, 3, 224, 224) # 4 gambar RGB 224x224
    dummy_qualities = torch.tensor([0.8, 0.5, 0.9, 0.3]) # 4 skor kualitas (0-1)

    # Jalankan model
    outputs = model(dummy_images, dummy_qualities)

    print("\n✅ TAHAP 3 SELESAI: Forward Pass Berhasil!")
    print(f"Shape Output: {outputs.shape}") # Harus [4, 2] (4 batch, 2 kelas)
    print(f"Hasil Logit Prediksi:\n{outputs}")

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm # Untuk progress bar yang rapi

# ======================================================
# 1. IMPLEMENTASI FOCAL LOSS (Mengatasi Imbalance)
# ======================================================
class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        """
        Focal Loss menekan nilai loss untuk contoh yang mudah ditebak (mayoritas)
        dan memaksa model fokus pada contoh yang sulit (minoritas GON-).
        """
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.reduction = reduction
        # Alpha digunakan untuk memberikan bobot ekstra pada kelas minoritas
        if alpha is not None:
            self.alpha = torch.tensor(alpha, dtype=torch.float32)
        else:
            self.alpha = None

    def forward(self, inputs, targets):
        # Hitung standard Cross Entropy Loss
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')

        # pt adalah probabilitas prediksi dari kelas yang benar
        pt = torch.exp(-ce_loss)

        # Terapkan faktor pemfokus (1 - pt)^gamma
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss

        if self.alpha is not None:
            alpha_t = self.alpha.to(inputs.device)[targets]
            focal_loss = alpha_t * focal_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        else:
            return focal_loss.sum()

# ======================================================
# 2. SETUP TRAINING LOOP & OPTIMISASI
# ======================================================
def train_model(model, train_loader, val_loader, num_epochs=5):
    # Pindahkan model ke GPU jika tersedia
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    print(f"--- Memulai Pelatihan menggunakan device: {device} ---")

    # Inisialisasi Focal Loss
    # Karena GON- (kelas 0) adalah minoritas 27%, kita beri bobot lebih tinggi (misal 0.73)
    # GON+ (kelas 1) adalah mayoritas 73%, kita beri bobot lebih rendah (misal 0.27)
    criterion = FocalLoss(alpha=[0.73, 0.27], gamma=2.0)

    # Optimizer AdamW (Varian Adam dengan Weight Decay yang lebih baik untuk Transformer)
    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)

    # Loop Pelatihan per Epoch
    for epoch in range(num_epochs):
        model.train() # Mode training (mengaktifkan Dropout & Gradient Tracking)
        running_loss = 0.0
        correct_preds = 0
        total_preds = 0

        print(f"\nEpoch {epoch+1}/{num_epochs}")
        # Progress bar menggunakan tqdm
        progress_bar = tqdm(train_loader, desc="Training", leave=False)

        for batch in progress_bar:
            # Pindahkan data ke GPU
            images = batch['image'].to(device)
            qualities = batch['quality'].to(device)
            labels = batch['label'].to(device)

            # 1. Zero Grad (Bersihkan sisa gradien dari iterasi sebelumnya)
            optimizer.zero_grad()

            # 2. Forward Pass (Prediksi)
            outputs = model(images, qualities)

            # 3. Hitung Focal Loss
            loss = criterion(outputs, labels)

            # 4. Backpropagation (Menghitung arah turunan/gradien)
            loss.backward()

            # 5. Optimization Step (Update bobot model bergerak menuju titik minimum loss)
            optimizer.step()

            # --- Perhitungan Metrik Akurasi Sederhana ---
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total_preds += labels.size(0)
            correct_preds += (predicted == labels).sum().item()

            progress_bar.set_postfix(loss=loss.item(), acc=(correct_preds/total_preds)*100)

        epoch_loss = running_loss / len(train_loader)
        epoch_acc = (correct_preds / total_preds) * 100
        print(f"Train Loss: {epoch_loss:.4f} | Train Acc: {epoch_acc:.2f}%")

        # --- (Opsional di sini: Tambahkan Validation Loop) ---

# ======================================================
# 3. EKSEKUSI TRAINING
# ======================================================
if __name__ == "__main__":
    # Asumsi model, train_loader, val_loader sudah ada di memory (dari Tahap 2 & 3)
    # Kita jalankan simulasi 1 epoch saja dulu untuk memastikan pipeline tidak error
    try:
        train_model(model, train_loader, val_loader, num_epochs=1)
        print("\n✅ TAHAP 4 SELESAI: Model berhasil melakukan Backpropagation dan Update Bobot!")
    except Exception as e:
        print(f"❌ Terjadi Error saat training: {e}")

import torch
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, classification_report

def evaluate_metrics(model, dataloader, device):
    print("--- Memulai Evaluasi Model ---")
    model.eval() # Penting: Matikan Dropout dan BatchNorm agar hasil konsisten

    all_labels = []
    all_preds = []
    all_probs = []

    # Matikan pelacakan gradien (menghemat memori dan mempercepat proses)
    with torch.no_grad():
        for batch in dataloader:
            images = batch['image'].to(device)
            qualities = batch['quality'].to(device)
            labels = batch['label'].to(device)

            # Forward pass
            outputs = model(images, qualities)

            # Hitung probabilitas menggunakan Softmax untuk kelas 1 (GON+)
            probs = torch.softmax(outputs, dim=1)[:, 1]
            # Ambil kelas dengan nilai logit tertinggi
            _, preds = torch.max(outputs, 1)

            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    # Hitung Metrik
    f1 = f1_score(all_labels, all_preds)
    auroc = roc_auc_score(all_labels, all_probs)
    cm = confusion_matrix(all_labels, all_preds)

    print(f"\n✅ Hasil Evaluasi:")
    print(f"F1-Score : {f1:.4f}")
    print(f"AUROC    : {auroc:.4f}")
    print("\nClassification Report:")
    print(classification_report(all_labels, all_preds, target_names=['GON-', 'GON+']))

    # Visualisasi Confusion Matrix
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['GON-', 'GON+'], yticklabels=['GON-', 'GON+'])
    plt.title('Confusion Matrix')
    plt.ylabel('Label Sebenarnya')
    plt.xlabel('Prediksi Model')
    plt.show()

# Cara menjalankan:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
evaluate_metrics(model, val_loader, device)

"""# PROGRAM VERSI 2"""

# Instalasi library yang dibutuhkan
!pip install timm
!pip install scikit-learn
!pip install seaborn
!pip install opencv-python

import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, classification_report, roc_curve
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
import timm
import cv2
import math
from tqdm import tqdm

# ======================================================
# 1. KONFIGURASI GLOBAL (Ganti path sesuai lokasi Google Drive-mu)
# ======================================================
# --- GANTI BAGIAN INI JIKA PERLU ---
BASE_PATH = '/content/drive/MyDrive/Competition/IDSC 2026/Dataset/hillel-yaffe-glaucoma-dataset/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0'
IMAGE_DIR = os.path.join(BASE_PATH, 'Images')
CSV_PATH = os.path.join(BASE_PATH, 'Labels.csv')
# -----------------------------------

# Set seed global untuk reproducibility
def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Menggunakan device: {device}")

# ======================================================
# 2. TAHAP 1: PREPARATION & SPLIT (Patient-Level)
# ======================================================
def prepare_and_split(csv_path):
    print("\n--- Membaca Metadata & Deteksi Kolom ---")
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    cols = df.columns.str.lower()
    col_img = df.columns[['image' in c or 'file' in c or 'name' in c for c in cols]][0]
    col_pat = df.columns[['patient' in c or 'id' in c for c in cols]][0]
    col_lab = df.columns[['diagnosis' in c or 'label' in c or 'gon' in c for c in cols]][0]
    col_qty = df.columns[['quality' in c or 'score' in c for c in cols]][0]

    # Split: 73% Train, 13.5% Val, 13.5% Test
    gss_test = GroupShuffleSplit(n_splits=1, test_size=0.135, random_state=42)
    train_val_idx, test_idx = next(gss_test.split(df, groups=df[col_pat]))
    df_train_val = df.iloc[train_val_idx].copy()
    df_test = df.iloc[test_idx].copy()

    gss_val = GroupShuffleSplit(n_splits=1, test_size=0.156, random_state=42)
    train_idx, val_idx = next(gss_val.split(df_train_val, groups=df_train_val[col_pat]))
    df_train = df_train_val.iloc[train_idx].copy()
    df_val = df_train_val.iloc[val_idx].copy()

    col_dict = {'img': col_img, 'pat': col_pat, 'lab': col_lab, 'qty': col_qty}
    print(f"✅ Data Terbagi! Train: {len(df_train)}, Val: {len(df_val)}, Test: {len(df_test)}")
    return df_train, df_val, df_test, col_dict

df_train, df_val, df_test, cols = prepare_and_split(CSV_PATH)

# ======================================================
# 3. TAHAP 2: PIPELINE AUGMENTASI & DATASET
# ======================================================
IMG_SIZE = 224

# Standar untuk Val & Test
val_test_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Standar untuk Train Mayoritas (GON+)
train_base_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Ekstrem untuk Train Minoritas (GON-) -> Meniru Paper Christopher et al.
train_aggressive_transform = T.Compose([
    T.RandomResizedCrop(IMG_SIZE, scale=(0.8, 1.0)),
    T.RandomHorizontalFlip(p=0.5),
    T.RandomVerticalFlip(p=0.5),
    T.RandomRotation(degrees=45),
    T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

class HYGDDataset(Dataset):
    def __init__(self, dataframe, root_dir, col_dict, is_train=False):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.cols = col_dict
        self.is_train = is_train

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_name = str(self.df.loc[idx, self.cols['img']])
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_name += '.jpg'
        img_path = os.path.join(self.root_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        raw_label = str(self.df.loc[idx, self.cols['lab']]).strip().upper()
        label = 1 if raw_label == 'GON+' else (0 if raw_label == 'GON-' else int(float(raw_label)))
        quality = float(self.df.loc[idx, self.cols['qty']]) / 10.0

        if self.is_train:
            if label == 0: # Minoritas (GON-) disiksa
                image = train_aggressive_transform(image)
            else:          # Mayoritas (GON+) biasa saja
                image = train_base_transform(image)
        else:
            image = val_test_transform(image)

        return {
            'image': image,
            'label': torch.tensor(label, dtype=torch.long),
            'quality': torch.tensor(quality, dtype=torch.float32)
        }

# Buat Dataloader
train_ds = HYGDDataset(df_train, IMAGE_DIR, cols, is_train=True)
val_ds = HYGDDataset(df_val, IMAGE_DIR, cols, is_train=False)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2)
val_loader = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=2)
print("✅ Dataloader Siap!")

# ======================================================
# 4. TAHAP 3: ARSITEKTUR MULTIMODAL SWIN (TRANSFER LEARNING)
# ======================================================
class QualityAwareSwin(nn.Module):
    def __init__(self, model_name='swin_base_patch4_window7_224', pretrained=True):
        super(QualityAwareSwin, self).__init__()
        # Transfer Learning AKTIF (pretrained=True)
        self.swin = timm.create_model(model_name, pretrained=pretrained, num_classes=0)
        swin_out_features = self.swin.num_features

        self.quality_mlp = nn.Sequential(
            nn.Linear(1, 16),
            nn.GELU(),
            nn.Linear(16, 16),
            nn.GELU()
        )

        self.classifier = nn.Sequential(
            nn.Linear(swin_out_features + 16, 512),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(512, 2)
        )

    def forward(self, image, quality_score):
        v_feat = self.swin(image)
        if quality_score.dim() == 1: quality_score = quality_score.unsqueeze(1)
        q_feat = self.quality_mlp(quality_score)
        fused = torch.cat((v_feat, q_feat), dim=1)
        return self.classifier(fused)

model = QualityAwareSwin().to(device)

# ======================================================
# 5. TAHAP 4: TRAINING DENGAN FOCAL LOSS
# ======================================================
class FocalLoss(nn.Module):
    def __init__(self, alpha=[0.85, 0.15], gamma=2.0): # Bobot ekstrem untuk imbalanced
        super(FocalLoss, self).__init__()
        self.alpha = torch.tensor(alpha, dtype=torch.float32).to(device)
        self.gamma = gamma

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = self.alpha[targets] * ((1 - pt) ** self.gamma) * ce_loss
        return focal_loss.mean()

# Parameter Training
epochs = 5 # Set ke 15-20 jika punya waktu luang
criterion = FocalLoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=2)

print("\n--- Memulai Training ---")
for epoch in range(epochs):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
    for batch in pbar:
        img, qty, lbl = batch['image'].to(device), batch['quality'].to(device), batch['label'].to(device)

        optimizer.zero_grad()
        out = model(img, qty)
        loss = criterion(out, lbl)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, pred = torch.max(out, 1)
        total += lbl.size(0)
        correct += (pred == lbl).sum().item()
        pbar.set_postfix(loss=loss.item())

    train_acc = correct/total * 100
    print(f"Epoch {epoch+1} | Loss: {running_loss/len(train_loader):.4f} | Acc: {train_acc:.2f}%")
    scheduler.step(running_loss)

# ======================================================
# 6. TAHAP 5: EVALUASI (THRESHOLD OPTIMAL)
# ======================================================
print("\n--- Evaluasi pada Validation Set ---")
model.eval()
all_lbl, all_prob = [], []

with torch.no_grad():
    for batch in val_loader:
        img, qty, lbl = batch['image'].to(device), batch['quality'].to(device), batch['label'].to(device)
        out = model(img, qty)
        prob = torch.softmax(out, dim=1)[:, 1] # Probabilitas kelas 1 (GON+)
        all_lbl.extend(lbl.cpu().numpy())
        all_prob.extend(prob.cpu().numpy())

all_lbl = np.array(all_lbl)
all_prob = np.array(all_prob)

# 1. AUROC Score
auroc = roc_auc_score(all_lbl, all_prob)
print(f"AUROC Score: {auroc:.4f}")

# 2. Cari Threshold Optimal (Youden's J)
fpr, tpr, thresholds = roc_curve(all_lbl, all_prob)
optimal_idx = np.argmax(tpr - fpr)
opt_thresh = thresholds[optimal_idx]
print(f"Ambang Batas Optimal: {opt_thresh:.4f}")

# 3. Klasifikasi menggunakan Threshold Optimal
opt_preds = (all_prob >= opt_thresh).astype(int)

# 4. Metrik Akhir
print("\nClassification Report (Dengan Optimal Threshold):")
print(classification_report(all_lbl, opt_preds, target_names=['GON-', 'GON+']))

# 5. Visualisasi Confusion Matrix
cm = confusion_matrix(all_lbl, opt_preds)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['GON-', 'GON+'], yticklabels=['GON-', 'GON+'])
plt.title(f'Confusion Matrix (Threshold={opt_thresh:.2f})')
plt.ylabel('Label Sebenarnya')
plt.xlabel('Prediksi Model')
plt.show()

# ======================================================
# 7. CUSTOM GRAD-CAM (TANPA LIBRARY LUAR)
# ======================================================
class MathGradCAM:
    def __init__(self, model, target_module):
        self.model = model
        self.feature_map, self.gradient = None, None
        target_module.register_forward_hook(self.save_feat)
        target_module.register_full_backward_hook(self.save_grad)

    def save_feat(self, mod, inp, out): self.feature_map = out.detach()
    def save_grad(self, mod, g_in, g_out): self.gradient = g_out[0].detach()

    def generate(self, img_tsr, qty_tsr, tgt_cls):
        self.model.eval()
        self.model.zero_grad()
        out = self.model(img_tsr, qty_tsr)
        out[0, tgt_cls].backward(retain_graph=True)

        feat, grad = self.feature_map[0], self.gradient[0]

        if feat.dim() == 2: # Fix format dari timm
            size = int(np.sqrt(feat.shape[0]))
            feat = feat.view(size, size, -1)
            grad = grad.view(size, size, -1)

        alpha = torch.mean(grad, dim=(0, 1))
        cam = torch.zeros(feat.shape[:2], dtype=torch.float32, device=feat.device)
        for i, w in enumerate(alpha): cam += w * feat[:, :, i]

        cam = F.relu(cam)
        cam = (cam - cam.min()) / (cam.max() + 1e-8)
        return cam.cpu().numpy()

# Visualisasi
def show_heatmap(idx):
    sample = val_ds[idx]
    img, qty, lbl = sample['image'].unsqueeze(0).to(device), sample['quality'].unsqueeze(0).to(device), sample['label'].item()

    grad_cam = MathGradCAM(model, model.swin.layers[-1].blocks[-1])
    cam_raw = grad_cam.generate(img, qty, lbl)

    cam_rsz = cv2.resize(cam_raw, (224, 224), interpolation=cv2.INTER_CUBIC)

    img_disp = np.clip(np.array([0.229, 0.224, 0.225]) * img.cpu().squeeze().permute(1, 2, 0).numpy() + np.array([0.485, 0.456, 0.406]), 0, 1)

    hm = np.float32(cv2.applyColorMap(np.uint8(255 * cam_rsz), cv2.COLORMAP_JET))[..., ::-1] / 255
    overlay = np.clip(hm * 0.4 + img_disp * 0.6, 0, 1)

    plt.figure(figsize=(10, 4))
    for i, (pic, tit) in enumerate(zip([img_disp, cam_rsz, overlay], ["Asli", "Aktivasi", "Overlay"])):
        plt.subplot(1, 3, i+1); plt.imshow(pic, cmap='jet' if i==1 else None); plt.title(tit); plt.axis('off')
    plt.suptitle(f"Kelas Asli: {'GON+' if lbl==1 else 'GON-'}", fontsize=14)
    plt.show()

print("\n--- Visualisasi Grad-CAM ---")
show_heatmap(0) # Ganti angka 0 dengan indeks data validasi lain untuk melihat gambar lain

"""#PROGRAM VERSI 3"""

# Instalasi library yang dibutuhkan
!pip install timm
!pip install scikit-learn
!pip install seaborn
!pip install opencv-python

import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, classification_report, roc_curve
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
import timm
import cv2
import math
from tqdm import tqdm

# ======================================================
# 1. KONFIGURASI GLOBAL (Ganti path sesuai lokasi Google Drive-mu)
# ======================================================
# --- GANTI BAGIAN INI JIKA PERLU ---
BASE_PATH = '/content/drive/MyDrive/Competition/IDSC 2026/Dataset/hillel-yaffe-glaucoma-dataset/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0'
IMAGE_DIR = os.path.join(BASE_PATH, 'Images')
CSV_PATH = os.path.join(BASE_PATH, 'Labels.csv')
# -----------------------------------

# Set seed global untuk reproducibility
def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Menggunakan device: {device}")

# ======================================================
# 2. TAHAP 1: PREPARATION & SPLIT (Patient-Level)
# ======================================================
def prepare_and_split(csv_path):
    print("\n--- Membaca Metadata & Deteksi Kolom ---")
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    cols = df.columns.str.lower()
    col_img = df.columns[['image' in c or 'file' in c or 'name' in c for c in cols]][0]
    col_pat = df.columns[['patient' in c or 'id' in c for c in cols]][0]
    col_lab = df.columns[['diagnosis' in c or 'label' in c or 'gon' in c for c in cols]][0]
    col_qty = df.columns[['quality' in c or 'score' in c for c in cols]][0]

    # Split: 73% Train, 13.5% Val, 13.5% Test
    gss_test = GroupShuffleSplit(n_splits=1, test_size=0.135, random_state=42)
    train_val_idx, test_idx = next(gss_test.split(df, groups=df[col_pat]))
    df_train_val = df.iloc[train_val_idx].copy()
    df_test = df.iloc[test_idx].copy()

    gss_val = GroupShuffleSplit(n_splits=1, test_size=0.156, random_state=42)
    train_idx, val_idx = next(gss_val.split(df_train_val, groups=df_train_val[col_pat]))
    df_train = df_train_val.iloc[train_idx].copy()
    df_val = df_train_val.iloc[val_idx].copy()

    col_dict = {'img': col_img, 'pat': col_pat, 'lab': col_lab, 'qty': col_qty}
    print(f"✅ Data Terbagi! Train: {len(df_train)}, Val: {len(df_val)}, Test: {len(df_test)}")
    return df_train, df_val, df_test, col_dict

df_train, df_val, df_test, cols = prepare_and_split(CSV_PATH)

# ======================================================
# 3. TAHAP 2: PIPELINE AUGMENTASI (ANTI-LEAKAGE)
# ======================================================
IMG_SIZE = 224

# Standar untuk Val & Test (TIDAK ADA AUGMENTASI, HANYA RESIZE)
val_test_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Augmentasi Menengah-Agresif UNTUK SEMUA KELAS (GON+ & GON-)
# Kita buat seragam agar model tidak memakai augmentasi sebagai 'sontekan'
train_transform = T.Compose([
    T.RandomResizedCrop(IMG_SIZE, scale=(0.85, 1.0)), # Crop acak
    T.RandomHorizontalFlip(p=0.5), # Flip Kanan-Kiri
    T.RandomVerticalFlip(p=0.5),   # Flip Atas-Bawah
    T.RandomRotation(degrees=30),  # Rotasi acak max 30 derajat
    T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2), # Variasi cahaya
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

class HYGDDataset(Dataset):
    def __init__(self, dataframe, root_dir, col_dict, is_train=False):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.cols = col_dict
        self.is_train = is_train

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_name = str(self.df.loc[idx, self.cols['img']])
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_name += '.jpg'
        img_path = os.path.join(self.root_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        raw_label = str(self.df.loc[idx, self.cols['lab']]).strip().upper()
        label = 1 if raw_label == 'GON+' else (0 if raw_label == 'GON-' else int(float(raw_label)))
        quality = float(self.df.loc[idx, self.cols['qty']]) / 10.0

        # Menerapkan transformasi yang ADIL
        if self.is_train:
            image = train_transform(image) # Berlaku untuk GON+ maupun GON-
        else:
            image = val_test_transform(image)

        return {
            'image': image,
            'label': torch.tensor(label, dtype=torch.long),
            'quality': torch.tensor(quality, dtype=torch.float32)
        }

# Buat Dataloader
train_ds = HYGDDataset(df_train, IMAGE_DIR, cols, is_train=True)
val_ds = HYGDDataset(df_val, IMAGE_DIR, cols, is_train=False)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2)
val_loader = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=2)
print("✅ Dataloader Baru Siap (Jebakan Augmentasi telah dihapus)!")

# ======================================================
# 4. TAHAP 3: ARSITEKTUR MULTIMODAL SWIN (TRANSFER LEARNING)
# ======================================================
class QualityAwareSwin(nn.Module):
    def __init__(self, model_name='swin_base_patch4_window7_224', pretrained=True):
        super(QualityAwareSwin, self).__init__()
        self.swin = timm.create_model(model_name, pretrained=pretrained, num_classes=0)
        swin_out_features = self.swin.num_features

        self.quality_mlp = nn.Sequential(
            nn.Linear(1, 16),
            nn.GELU(),
            nn.Linear(16, 16),
            nn.GELU()
        )

        self.classifier = nn.Sequential(
            nn.Linear(swin_out_features + 16, 512),
            nn.GELU(),
            nn.Dropout(0.5), # Naikkan dropout untuk mencegah model menghafal
            nn.Linear(512, 2)
        )

    def forward(self, image, quality_score):
        v_feat = self.swin(image)
        if quality_score.dim() == 1: quality_score = quality_score.unsqueeze(1)
        q_feat = self.quality_mlp(quality_score)
        fused = torch.cat((v_feat, q_feat), dim=1)
        return self.classifier(fused)

model = QualityAwareSwin().to(device)

# --- STRATEGI ANTI-OVERFITTING: FREEZE SWIN BACKBONE ---
print("--- Mengunci (Freeze) Layer Swin Transformer ---")
for param in model.swin.parameters():
    param.requires_grad = False

# Pastikan MLP dan Classifier tetap bisa belajar
for param in model.quality_mlp.parameters():
    param.requires_grad = True
for param in model.classifier.parameters():
    param.requires_grad = True

# ======================================================
# 5. TAHAP 4: TRAINING DENGAN FOCAL LOSS & EVALUASI
# ======================================================
class FocalLoss(nn.Module):
    def __init__(self, alpha=[0.75, 0.25], gamma=2.0): # Parameter diperhalus
        super(FocalLoss, self).__init__()
        self.alpha = torch.tensor(alpha, dtype=torch.float32).to(device)
        self.gamma = gamma

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = self.alpha[targets] * ((1 - pt) ** self.gamma) * ce_loss
        return focal_loss.mean()

epochs = 15 # Kita jalankan 15 epoch agar pola grafiknya terlihat
criterion = FocalLoss()

# LR diturunkan 10x lipat (1e-5), Weight Decay dinaikkan (0.05)
# Kita hanya meng-optimasi parameter yang requires_grad=True
optimizer = optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-5, weight_decay=0.05)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=2)

# --- LIST UNTUK MENYIMPAN HISTORY TRAINING ---
history = {
    'train_loss': [], 'val_loss': [],
    'train_acc': [], 'val_acc': []
}

print(f"\n--- Memulai Training selama {epochs} Epochs ---")
for epoch in range(epochs):
    # --- FASE TRAINING ---
    model.train()
    running_train_loss, correct_train, total_train = 0.0, 0, 0

    pbar_train = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [Train]")
    for batch in pbar_train:
        img, qty, lbl = batch['image'].to(device), batch['quality'].to(device), batch['label'].to(device)

        optimizer.zero_grad()
        out = model(img, qty)
        loss = criterion(out, lbl)
        loss.backward()
        optimizer.step()

        running_train_loss += loss.item()
        _, pred = torch.max(out, 1)
        total_train += lbl.size(0)
        correct_train += (pred == lbl).sum().item()
        pbar_train.set_postfix(loss=loss.item())

    epoch_train_loss = running_train_loss / len(train_loader)
    epoch_train_acc = correct_train / total_train * 100

    # --- FASE VALIDATION ---
    model.eval()
    running_val_loss, correct_val, total_val = 0.0, 0, 0

    with torch.no_grad():
        for batch in val_loader:
            img, qty, lbl = batch['image'].to(device), batch['quality'].to(device), batch['label'].to(device)
            out = model(img, qty)
            loss = criterion(out, lbl)

            running_val_loss += loss.item()
            _, pred = torch.max(out, 1)
            total_val += lbl.size(0)
            correct_val += (pred == lbl).sum().item()

    epoch_val_loss = running_val_loss / len(val_loader)
    epoch_val_acc = correct_val / total_val * 100

    # Simpan ke history
    history['train_loss'].append(epoch_train_loss)
    history['val_loss'].append(epoch_val_loss)
    history['train_acc'].append(epoch_train_acc)
    history['val_acc'].append(epoch_val_acc)

    print(f"Epoch {epoch+1} Hasil -> Train Loss: {epoch_train_loss:.4f} | Val Loss: {epoch_val_loss:.4f} | Train Acc: {epoch_train_acc:.2f}% | Val Acc: {epoch_val_acc:.2f}%")

    # Update scheduler berdasarkan Val Loss
    scheduler.step(epoch_val_loss)

# ======================================================
# VISUALISASI LEARNING CURVES
# ======================================================
plt.figure(figsize=(12, 5))

# Grafik 1: Akurasi
plt.subplot(1, 2, 1)
plt.plot(range(1, epochs+1), history['train_acc'], label='Train Accuracy', marker='o')
plt.plot(range(1, epochs+1), history['val_acc'], label='Validation Accuracy', marker='s')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True)

# Grafik 2: Loss
plt.subplot(1, 2, 2)
plt.plot(range(1, epochs+1), history['train_loss'], label='Train Loss', marker='o', color='red')
plt.plot(range(1, epochs+1), history['val_loss'], label='Validation Loss', marker='s', color='orange')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# ======================================================
# 6. TAHAP 5: EVALUASI & THRESHOLD OPTIMIZATION (F1-MAX)
# ======================================================
import numpy as np
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

print("\n--- Evaluasi pada Validation Set ---")
model.eval()
all_lbl, all_prob = [], []

with torch.no_grad():
    for batch in val_loader:
        img, qty, lbl = batch['image'].to(device), batch['quality'].to(device), batch['label'].to(device)
        out = model(img, qty)
        prob = torch.softmax(out, dim=1)[:, 1] # Ambil probabilitas untuk GON+
        all_lbl.extend(lbl.cpu().numpy())
        all_prob.extend(prob.cpu().numpy())

all_lbl = np.array(all_lbl)
all_prob = np.array(all_prob)

# 1. Hitung AUROC Mentah
auroc = roc_auc_score(all_lbl, all_prob)
print(f"AUROC Score: {auroc:.4f} (Semakin mendekati 1.0 semakin baik model membedakan kelas)")

# 2. Simulasi Pencarian Threshold berdasarkan F1-Score
thresholds = np.linspace(0.0, 1.0, 100) # Buat 100 titik uji dari 0 sampai 1
f1_scores = []

for t in thresholds:
    preds = (all_prob >= t).astype(int)
    # Rata-rata harmonik (macro) agar adil untuk GON+ dan GON-
    f1 = f1_score(all_lbl, preds, average='macro')
    f1_scores.append(f1)

# Ambil threshold yang menghasilkan F1-Score tertinggi
optimal_idx = np.argmax(f1_scores)
opt_thresh = thresholds[optimal_idx]
best_f1 = f1_scores[optimal_idx]

print(f"⭐ Ambang Batas (Threshold) Paling Optimal: {opt_thresh:.4f}")
print(f"🏆 F1-Score Macro Maksimal: {best_f1:.4f}")

# 3. Terapkan Threshold Tersebut
opt_preds = (all_prob >= opt_thresh).astype(int)

# 4. Tampilkan Classification Report
print("\nClassification Report (Dengan Optimal Threshold):")
print(classification_report(all_lbl, opt_preds, target_names=['GON-', 'GON+']))

# 5. Visualisasi Analisis Threshold & Confusion Matrix
plt.figure(figsize=(12, 5))

# Plot Kurva F1 vs Threshold
plt.subplot(1, 2, 1)
plt.plot(thresholds, f1_scores, label='F1-Score (Macro)', color='purple', linewidth=2)
plt.axvline(x=opt_thresh, color='red', linestyle='--', label=f'Optimal: {opt_thresh:.2f}')
plt.title('Optimalisasi Ambang Batas (Threshold Tuning)')
plt.xlabel('Nilai Threshold')
plt.ylabel('F1-Score')
plt.legend()
plt.grid(True)

# Plot Confusion Matrix
cm = confusion_matrix(all_lbl, opt_preds)
plt.subplot(1, 2, 2)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['GON-', 'GON+'], yticklabels=['GON-', 'GON+'])
plt.title(f'Confusion Matrix (Threshold={opt_thresh:.2f})')
plt.ylabel('Label Sebenarnya')
plt.xlabel('Prediksi Model')

plt.tight_layout()
plt.show()

# ======================================================
# 7. TAHAP 6: VISUALISASI KLINIS UNTUK THE INSIGHTS
# ======================================================

# ------------------------------------------------------
# A. Definisi Mesin Grad-CAM (Satu baris ditambahkan untuk mengatasi error NoneType)
# ------------------------------------------------------
class MathGradCAM:
    def __init__(self, model, target_module):
        self.model = model
        self.feature_map, self.gradient = None, None
        target_module.register_forward_hook(self.save_feat)
        target_module.register_full_backward_hook(self.save_grad)

    def save_feat(self, mod, inp, out): self.feature_map = out.detach()
    def save_grad(self, mod, g_in, g_out): self.gradient = g_out[0].detach()

    def generate(self, img_tsr, qty_tsr, tgt_cls):
        self.model.eval()
        self.model.zero_grad()

        # BARIS SAKTI: Memaksa PyTorch mengaktifkan gradien meskipun backbone Swin di-freeze
        img_tsr.requires_grad_()

        out = self.model(img_tsr, qty_tsr)
        out[0, tgt_cls].backward(retain_graph=True)

        feat, grad = self.feature_map[0], self.gradient[0]

        if feat.dim() == 2: # Fix format output Swin Transformer
            size = int(np.sqrt(feat.shape[0]))
            feat = feat.view(size, size, -1)
            grad = grad.view(size, size, -1)

        alpha = torch.mean(grad, dim=(0, 1))
        cam = torch.zeros(feat.shape[:2], dtype=torch.float32, device=feat.device)
        for i, w in enumerate(alpha): cam += w * feat[:, :, i]

        cam = F.relu(cam)
        cam = (cam - cam.min()) / (cam.max() + 1e-8)
        return cam.cpu().detach().numpy()

# ------------------------------------------------------
# B. Definisi Fungsi Pelukis Peta Panas
# ------------------------------------------------------
def show_heatmap(dataset, idx, optimal_threshold=0.5):
    sample = dataset[idx]
    img = sample['image'].unsqueeze(0).to(device)
    qty = sample['quality'].unsqueeze(0).to(device)
    lbl = sample['label'].item()

    # 1. Melakukan Prediksi
    model.eval()
    with torch.no_grad():
        out = model(img, qty)
        prob_gon_plus = torch.softmax(out, dim=1)[0, 1].item()
        pred_label = 1 if prob_gon_plus >= optimal_threshold else 0

    # 2. Ekstraksi Fitur (Mencari tanda GON+ / kelas 1)
    target_class = 1
    grad_cam = MathGradCAM(model, model.swin.layers[-1].blocks[-1])
    cam_raw = grad_cam.generate(img, qty, tgt_cls=target_class)

    # 3. Denormalisasi Gambar Asli (Mengembalikan warna)
    cam_rsz = cv2.resize(cam_raw, (224, 224), interpolation=cv2.INTER_CUBIC)
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    img_disp = np.clip(std * img.cpu().squeeze().permute(1, 2, 0).detach().numpy() + mean, 0, 1)

    # 4. Membuat Overlay
    hm = np.float32(cv2.applyColorMap(np.uint8(255 * cam_rsz), cv2.COLORMAP_JET))[..., ::-1] / 255
    overlay = np.clip(hm * 0.4 + img_disp * 0.6, 0, 1)

    # 5. Menampilkan Grafik
    plt.figure(figsize=(12, 4))
    for i, (pic, tit) in enumerate(zip([img_disp, cam_rsz, overlay], ["Asli", "Peta Aktivasi GON+", "Overlay Model"])):
        plt.subplot(1, 3, i+1)
        plt.imshow(pic, cmap='jet' if i==1 else None)
        plt.title(tit, fontsize=11)
        plt.axis('off')

    # 6. Menentukan Warna Teks Judul (Hijau=Benar, Merah=Salah)
    str_asli = 'GON+' if lbl==1 else 'GON-'
    str_pred = 'GON+' if pred_label==1 else 'GON-'
    color = 'green' if str_asli == str_pred else 'red'

    plt.suptitle(f"Diagnosis Asli: {str_asli} | Tebakan Model: {str_pred} (Probabilitas GON+: {prob_gon_plus:.2f})",
                 fontsize=14, fontweight='bold', color=color)
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------
# C. Eksekusi Akhir pada Test Set
# ------------------------------------------------------
print("\n--- Visualisasi The Insights pada Test Set ---")

# WAJIB: Membungkus df_test menjadi format Dataset agar bisa diproses PyTorch
test_ds = HYGDDataset(df_test, IMAGE_DIR, cols, is_train=False)

# Menggunakan Threshold yang didapat dari Tahap 5 secara otomatis
OPT_THRESH = opt_thresh

# Menampilkan Laporan untuk 3 Pasien Pertama di Test Set
for i in range(3):
    show_heatmap(test_ds, idx=i, optimal_threshold=OPT_THRESH)