# -*- coding: utf-8 -*-
"""IDSC_DAFFA_HYGD-PT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vcvPynoq07eNf9smQLbxgBDCCmA8NAb
"""

# Instalasi library yang dibutuhkan
!pip install timm
!pip install scikit-learn
!pip install seaborn
!pip install opencv-python

import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, classification_report, roc_curve
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
import timm
import cv2
import math
from tqdm import tqdm

# ======================================================
# 1. KONFIGURASI GLOBAL (Ganti path sesuai lokasi Google Drive-mu)
# ======================================================
# --- GANTI BAGIAN INI JIKA PERLU ---
BASE_PATH = '/content/drive/MyDrive/Competition/IDSC 2026/Dataset/hillel-yaffe-glaucoma-dataset/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0'
IMAGE_DIR = os.path.join(BASE_PATH, 'Images')
CSV_PATH = os.path.join(BASE_PATH, 'Labels.csv')
# -----------------------------------

# Set seed global untuk reproducibility
def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Menggunakan device: {device}")

# ======================================================
# 2. TAHAP 1: PREPARATION & SPLIT (Patient-Level)
# ======================================================
def prepare_and_split(csv_path):
    print("\n--- Membaca Metadata & Deteksi Kolom ---")
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    cols = df.columns.str.lower()
    col_img = df.columns[['image' in c or 'file' in c or 'name' in c for c in cols]][0]
    col_pat = df.columns[['patient' in c or 'id' in c for c in cols]][0]
    col_lab = df.columns[['diagnosis' in c or 'label' in c or 'gon' in c for c in cols]][0]
    col_qty = df.columns[['quality' in c or 'score' in c for c in cols]][0]

    # Split: 73% Train, 13.5% Val, 13.5% Test
    gss_test = GroupShuffleSplit(n_splits=1, test_size=0.135, random_state=42)
    train_val_idx, test_idx = next(gss_test.split(df, groups=df[col_pat]))
    df_train_val = df.iloc[train_val_idx].copy()
    df_test = df.iloc[test_idx].copy()

    gss_val = GroupShuffleSplit(n_splits=1, test_size=0.156, random_state=42)
    train_idx, val_idx = next(gss_val.split(df_train_val, groups=df_train_val[col_pat]))
    df_train = df_train_val.iloc[train_idx].copy()
    df_val = df_train_val.iloc[val_idx].copy()

    col_dict = {'img': col_img, 'pat': col_pat, 'lab': col_lab, 'qty': col_qty}
    print(f"✅ Data Terbagi! Train: {len(df_train)}, Val: {len(df_val)}, Test: {len(df_test)}")
    return df_train, df_val, df_test, col_dict

df_train, df_val, df_test, cols = prepare_and_split(CSV_PATH)

# ======================================================
# 3. TAHAP 2: PIPELINE AUGMENTASI & DATASET
# ======================================================
IMG_SIZE = 224

# Standar untuk Val & Test
val_test_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Standar untuk Train Mayoritas (GON+)
train_base_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Ekstrem untuk Train Minoritas (GON-) -> Meniru Paper Christopher et al.
train_aggressive_transform = T.Compose([
    T.RandomResizedCrop(IMG_SIZE, scale=(0.8, 1.0)),
    T.RandomHorizontalFlip(p=0.5),
    T.RandomVerticalFlip(p=0.5),
    T.RandomRotation(degrees=45),
    T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

class HYGDDataset(Dataset):
    def __init__(self, dataframe, root_dir, col_dict, is_train=False):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.cols = col_dict
        self.is_train = is_train

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_name = str(self.df.loc[idx, self.cols['img']])
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_name += '.jpg'
        img_path = os.path.join(self.root_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        raw_label = str(self.df.loc[idx, self.cols['lab']]).strip().upper()
        label = 1 if raw_label == 'GON+' else (0 if raw_label == 'GON-' else int(float(raw_label)))
        quality = float(self.df.loc[idx, self.cols['qty']]) / 10.0

        if self.is_train:
            if label == 0: # Minoritas (GON-) disiksa
                image = train_aggressive_transform(image)
            else:          # Mayoritas (GON+) biasa saja
                image = train_base_transform(image)
        else:
            image = val_test_transform(image)

        return {
            'image': image,
            'label': torch.tensor(label, dtype=torch.long),
            'quality': torch.tensor(quality, dtype=torch.float32)
        }

# Buat Dataloader
train_ds = HYGDDataset(df_train, IMAGE_DIR, cols, is_train=True)
val_ds = HYGDDataset(df_val, IMAGE_DIR, cols, is_train=False)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2)
val_loader = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=2)
print("✅ Dataloader Siap!")

# ======================================================
# 4. TAHAP 3: ARSITEKTUR MULTIMODAL SWIN (TRANSFER LEARNING)
# ======================================================
class QualityAwareSwin(nn.Module):
    def __init__(self, model_name='swin_base_patch4_window7_224', pretrained=True):
        super(QualityAwareSwin, self).__init__()
        # Transfer Learning AKTIF (pretrained=True)
        self.swin = timm.create_model(model_name, pretrained=pretrained, num_classes=0)
        swin_out_features = self.swin.num_features

        self.quality_mlp = nn.Sequential(
            nn.Linear(1, 16),
            nn.GELU(),
            nn.Linear(16, 16),
            nn.GELU()
        )

        self.classifier = nn.Sequential(
            nn.Linear(swin_out_features + 16, 512),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(512, 2)
        )

    def forward(self, image, quality_score):
        v_feat = self.swin(image)
        if quality_score.dim() == 1: quality_score = quality_score.unsqueeze(1)
        q_feat = self.quality_mlp(quality_score)
        fused = torch.cat((v_feat, q_feat), dim=1)
        return self.classifier(fused)

model = QualityAwareSwin().to(device)

# ======================================================
# 5. TAHAP 4: TRAINING DENGAN FOCAL LOSS
# ======================================================
class FocalLoss(nn.Module):
    def __init__(self, alpha=[0.85, 0.15], gamma=2.0): # Bobot ekstrem untuk imbalanced
        super(FocalLoss, self).__init__()
        self.alpha = torch.tensor(alpha, dtype=torch.float32).to(device)
        self.gamma = gamma

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = self.alpha[targets] * ((1 - pt) ** self.gamma) * ce_loss
        return focal_loss.mean()

# Parameter Training
epochs = 5 # Set ke 15-20 jika punya waktu luang
criterion = FocalLoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=2)

print("\n--- Memulai Training ---")
for epoch in range(epochs):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
    for batch in pbar:
        img, qty, lbl = batch['image'].to(device), batch['quality'].to(device), batch['label'].to(device)

        optimizer.zero_grad()
        out = model(img, qty)
        loss = criterion(out, lbl)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, pred = torch.max(out, 1)
        total += lbl.size(0)
        correct += (pred == lbl).sum().item()
        pbar.set_postfix(loss=loss.item())

    train_acc = correct/total * 100
    print(f"Epoch {epoch+1} | Loss: {running_loss/len(train_loader):.4f} | Acc: {train_acc:.2f}%")
    scheduler.step(running_loss)

# ======================================================
# 6. TAHAP 5: EVALUASI (THRESHOLD OPTIMAL)
# ======================================================
print("\n--- Evaluasi pada Validation Set ---")
model.eval()
all_lbl, all_prob = [], []

with torch.no_grad():
    for batch in val_loader:
        img, qty, lbl = batch['image'].to(device), batch['quality'].to(device), batch['label'].to(device)
        out = model(img, qty)
        prob = torch.softmax(out, dim=1)[:, 1] # Probabilitas kelas 1 (GON+)
        all_lbl.extend(lbl.cpu().numpy())
        all_prob.extend(prob.cpu().numpy())

all_lbl = np.array(all_lbl)
all_prob = np.array(all_prob)

# 1. AUROC Score
auroc = roc_auc_score(all_lbl, all_prob)
print(f"AUROC Score: {auroc:.4f}")

# 2. Cari Threshold Optimal (Youden's J)
fpr, tpr, thresholds = roc_curve(all_lbl, all_prob)
optimal_idx = np.argmax(tpr - fpr)
opt_thresh = thresholds[optimal_idx]
print(f"Ambang Batas Optimal: {opt_thresh:.4f}")

# 3. Klasifikasi menggunakan Threshold Optimal
opt_preds = (all_prob >= opt_thresh).astype(int)

# 4. Metrik Akhir
print("\nClassification Report (Dengan Optimal Threshold):")
print(classification_report(all_lbl, opt_preds, target_names=['GON-', 'GON+']))

# 5. Visualisasi Confusion Matrix
cm = confusion_matrix(all_lbl, opt_preds)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['GON-', 'GON+'], yticklabels=['GON-', 'GON+'])
plt.title(f'Confusion Matrix (Threshold={opt_thresh:.2f})')
plt.ylabel('Label Sebenarnya')
plt.xlabel('Prediksi Model')
plt.show()

# ======================================================
# 7. CUSTOM GRAD-CAM (TANPA LIBRARY LUAR)
# ======================================================
class MathGradCAM:
    def __init__(self, model, target_module):
        self.model = model
        self.feature_map, self.gradient = None, None
        target_module.register_forward_hook(self.save_feat)
        target_module.register_full_backward_hook(self.save_grad)

    def save_feat(self, mod, inp, out): self.feature_map = out.detach()
    def save_grad(self, mod, g_in, g_out): self.gradient = g_out[0].detach()

    def generate(self, img_tsr, qty_tsr, tgt_cls):
        self.model.eval()
        self.model.zero_grad()
        out = self.model(img_tsr, qty_tsr)
        out[0, tgt_cls].backward(retain_graph=True)

        feat, grad = self.feature_map[0], self.gradient[0]

        if feat.dim() == 2: # Fix format dari timm
            size = int(np.sqrt(feat.shape[0]))
            feat = feat.view(size, size, -1)
            grad = grad.view(size, size, -1)

        alpha = torch.mean(grad, dim=(0, 1))
        cam = torch.zeros(feat.shape[:2], dtype=torch.float32, device=feat.device)
        for i, w in enumerate(alpha): cam += w * feat[:, :, i]

        cam = F.relu(cam)
        cam = (cam - cam.min()) / (cam.max() + 1e-8)
        return cam.cpu().numpy()

# Visualisasi
def show_heatmap(idx):
    sample = val_ds[idx]
    img, qty, lbl = sample['image'].unsqueeze(0).to(device), sample['quality'].unsqueeze(0).to(device), sample['label'].item()

    grad_cam = MathGradCAM(model, model.swin.layers[-1].blocks[-1])
    cam_raw = grad_cam.generate(img, qty, lbl)

    cam_rsz = cv2.resize(cam_raw, (224, 224), interpolation=cv2.INTER_CUBIC)

    img_disp = np.clip(np.array([0.229, 0.224, 0.225]) * img.cpu().squeeze().permute(1, 2, 0).numpy() + np.array([0.485, 0.456, 0.406]), 0, 1)

    hm = np.float32(cv2.applyColorMap(np.uint8(255 * cam_rsz), cv2.COLORMAP_JET))[..., ::-1] / 255
    overlay = np.clip(hm * 0.4 + img_disp * 0.6, 0, 1)

    plt.figure(figsize=(10, 4))
    for i, (pic, tit) in enumerate(zip([img_disp, cam_rsz, overlay], ["Asli", "Aktivasi", "Overlay"])):
        plt.subplot(1, 3, i+1); plt.imshow(pic, cmap='jet' if i==1 else None); plt.title(tit); plt.axis('off')
    plt.suptitle(f"Kelas Asli: {'GON+' if lbl==1 else 'GON-'}", fontsize=14)
    plt.show()

print("\n--- Visualisasi Grad-CAM ---")
show_heatmap(0) # Ganti angka 0 dengan indeks data validasi lain untuk melihat gambar lain

