# -*- coding: utf-8 -*-
"""IDSC_DAFFA_HYGD-PT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fzy73Jdrd5UqQ_alTAJvEJbIeFSTTs12
"""

!pip install timm
!pip install timm seaborn scikit-learn

import os
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import timm
from sklearn.model_selection import GroupShuffleSplit
from PIL import Image
import matplotlib.pyplot as plt
import torchvision.transforms as T
import numpy as np
from tqdm import tqdm # Untuk progress bar yang rapi
import seaborn as sns
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, classification_report

# ======================================================
# 1. KONFIGURASI PATH
# ======================================================
BASE_PATH = '/content/drive/MyDrive/Competition/IDSC 2026/Dataset/hillel-yaffe-glaucoma-dataset/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0'
IMAGE_DIR = os.path.join(BASE_PATH, 'Images')
CSV_PATH = os.path.join(BASE_PATH, 'Labels.csv')

# ======================================================
# 2. AUTO-MAPPER & SPLITTER (TAHAP 1 AMAN DARI ERROR)
# ======================================================
def prepare_and_split(csv_path):
    print("--- Membaca Metadata & Deteksi Kolom ---")
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip() # Bersihkan spasi tersembunyi

    cols = df.columns.str.lower()

    # Deteksi dinamis 4 kolom utama
    try:
        col_img = df.columns[['image' in c or 'file' in c or 'name' in c for c in cols]][0]
        col_pat = df.columns[['patient' in c or 'id' in c for c in cols]][0]
        col_lab = df.columns[['diagnosis' in c or 'label' in c or 'gon' in c for c in cols]][0]
        col_qty = df.columns[['quality' in c or 'score' in c for c in cols]][0]
    except IndexError:
        print(f"❌ ERROR: Tidak dapat memetakan kolom. Kolom yang tersedia: {list(df.columns)}")
        raise

    print(f"✅ Pemetaan Kolom Berhasil:")
    print(f"   - Gambar  : '{col_img}'")
    print(f"   - Pasien  : '{col_pat}'")
    print(f"   - Label   : '{col_lab}'")
    print(f"   - Kualitas: '{col_qty}'")

    # Patient-Level Split (73% Train, 13.5% Val, 13.5% Test)
    # Split 1: Ambil 13.5% untuk Test (menyisakan 86.5% untuk Train+Val)
    gss_test = GroupShuffleSplit(n_splits=1, test_size=0.135, random_state=42)
    train_val_idx, test_idx = next(gss_test.split(df, groups=df[col_pat]))

    df_train_val = df.iloc[train_val_idx].copy()
    df_test = df.iloc[test_idx].copy()

    # Split 2: Bagi sisa 86.5% agar Val mendapat porsi 13.5% dari total data (13.5 / 86.5 = 0.156)
    gss_val = GroupShuffleSplit(n_splits=1, test_size=0.156, random_state=42)
    train_idx, val_idx = next(gss_val.split(df_train_val, groups=df_train_val[col_pat]))

    df_train = df_train_val.iloc[train_idx].copy()
    df_val = df_train_val.iloc[val_idx].copy()

    print(f"\n✅ Data Terbagi! Train: {len(df_train)}, Val: {len(df_val)}, Test: {len(df_test)}")

    # Kembalikan dataframe dan dictionary nama kolom agar Dataset Class tidak error
    col_dict = {'img': col_img, 'pat': col_pat, 'lab': col_lab, 'qty': col_qty}
    return df_train, df_val, df_test, col_dict

# ======================================================
# 3. CLASS DATASET YANG FLEKSIBEL (FIXED LABEL CONVERSION)
# ======================================================
class HYGDDataset(Dataset):
    def __init__(self, dataframe, root_dir, col_dict, transform=None):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.cols = col_dict
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # 1. Load Nama Gambar & Fisik Gambar
        img_name = str(self.df.loc[idx, self.cols['img']])
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_name += '.jpg'

        img_path = os.path.join(self.root_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        # 2. Konversi Label Teks ('GON+' / 'GON-') ke Angka (1 / 0)
        raw_label = str(self.df.loc[idx, self.cols['lab']]).strip().upper()
        if raw_label == 'GON+':
            label = 1
        elif raw_label == 'GON-':
            label = 0
        else:
            # Jaga-jaga jika ternyata isinya sudah berbentuk angka 1 atau 0 dari CSV-nya
            try:
                label = int(float(raw_label))
            except ValueError:
                label = 0 # Default fallback

        # 3. Normalisasi Quality Score (0 - 1)
        quality = float(self.df.loc[idx, self.cols['qty']]) / 10.0

        if self.transform:
            image = self.transform(image)

        return {
            'image': image,
            'label': torch.tensor(label, dtype=torch.long),
            'quality': torch.tensor(quality, dtype=torch.float32)
        }

# ======================================================
# 4. EKSEKUSI & TEST TAHAP 1
# ======================================================
if __name__ == "__main__":
    try:
        # 1. Jalankan Split & Mapper
        df_train, df_val, df_test, cols = prepare_and_split(CSV_PATH)

        # 2. Setup Transform & Loader
        test_transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
        ])

        train_ds = HYGDDataset(df_train, IMAGE_DIR, cols, transform=test_transform)
        train_loader = DataLoader(train_ds, batch_size=4, shuffle=True)

        # 3. Ambil 1 batch untuk verifikasi akhir
        batch = next(iter(train_loader))
        print("\n--- Verifikasi Batch Gambar ---")
        print(f"Shape Tensor Gambar: {batch['image'].shape}")
        print(f"Label GON+/GON-    : {batch['label']}")
        print(f"Skor Kualitas (0-1): {batch['quality']}")
        print("✅ TAHAP 1 SELESAI DAN AMAN DARI ERROR!")

    except FileNotFoundError:
        print("\n❌ File tidak ditemukan. Pastikan Google Drive sudah di-mount:")
        print("from google.colab import drive\ndrive.mount('/content/drive')")
    except Exception as e:
        print(f"\n❌ Terjadi Error Lain: {e}")

# ======================================================
# 1. DEFINISI PIPELINE TRANSFORMASI (TAHAP 2)
# ======================================================
IMG_SIZE = 224 # Sesuai diagram: Resize ke 224x224 (atau 384x384)

# A. Transformasi Standar (Untuk Val & Test Set)
val_test_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # Standar ImageNet
])

# B. Transformasi Dasar (Untuk Train Set kelas mayoritas GON+)
train_base_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5), # Augmentasi ringan
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# C. Transformasi Agresif (Khusus Train Set kelas minoritas GON-)
train_aggressive_transform = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5),
    T.RandomVerticalFlip(p=0.5),
    T.RandomRotation(degrees=30), # Putar acak hingga 30 derajat
    T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05), # Ubah pencahayaan
    T.RandomAffine(degrees=0, translate=(0.1, 0.1)), # Geser gambar sedikit
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# ======================================================
# 2. UPDATE CLASS DATASET (Conditional Augmentation)
# ======================================================
class HYGDDatasetV2(Dataset):
    def __init__(self, dataframe, root_dir, col_dict, is_train=False):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.cols = col_dict
        self.is_train = is_train # Penanda apakah ini data training

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # 1. Load Gambar
        img_name = str(self.df.loc[idx, self.cols['img']])
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_name += '.jpg'
        img_path = os.path.join(self.root_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        # 2. Load Label & Quality Score
        raw_label = str(self.df.loc[idx, self.cols['lab']]).strip().upper()
        label = 1 if raw_label == 'GON+' else (0 if raw_label == 'GON-' else int(float(raw_label)))
        quality = float(self.df.loc[idx, self.cols['qty']]) / 10.0

        # 3. Terapkan Transformasi Bersyarat (Inti dari Tahap 2)
        if self.is_train:
            if label == 0: # Minoritas GON- (27%)
                image = train_aggressive_transform(image)
            else:          # Mayoritas GON+ (73%)
                image = train_base_transform(image)
        else:
            # Jika Val / Test, selalu gunakan transformasi standar
            image = val_test_transform(image)

        return {
            'image': image,
            'label': torch.tensor(label, dtype=torch.long),
            'quality': torch.tensor(quality, dtype=torch.float32)
        }

# ======================================================
# 3. INISIALISASI DATALOADER FINAL TAHAP 2
# ======================================================
if __name__ == "__main__":
    # Menggunakan df_train, df_val, df_test, dan cols dari Tahap 1 sebelumnya

    # Buat Dataset (Perhatikan parameter is_train)
    train_ds = HYGDDatasetV2(df_train, IMAGE_DIR, cols, is_train=True)
    val_ds = HYGDDatasetV2(df_val, IMAGE_DIR, cols, is_train=False)
    test_ds = HYGDDatasetV2(df_test, IMAGE_DIR, cols, is_train=False)

    # Buat DataLoader
    train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_ds, batch_size=16, shuffle=False, num_workers=2)

    print("✅ TAHAP 2 SELESAI: Pipeline Preprocessing & Augmentasi Agresif berhasil dibuat!")
    print(f"Jumlah Batch per Epoch (Train): {len(train_loader)}")

# ======================================================
# ARSITEKTUR TAHAP 3: QUALITY-AWARE SWIN TRANSFORMER
# ======================================================
class QualityAwareSwin(nn.Module):
    def __init__(self, model_name='swin_base_patch4_window7_224', pretrained=True, num_classes=2):
        super(QualityAwareSwin, self).__init__()

        # ---------------------------------------------------
        # 1. CABANG VISUAL (SWIN TRANSFORMER BACKBONE)
        # ---------------------------------------------------
        # num_classes=0 membuang layer klasifikasi asli bawaan ImageNet
        # Ini menyisakan kita dengan 'Visual Feature Vector' (Pooling Layer)
        self.swin = timm.create_model(model_name, pretrained=pretrained, num_classes=0)

        # Mengambil dimensi output dari Swin (Biasanya 1024 untuk swin_base)
        swin_out_features = self.swin.num_features

        # ---------------------------------------------------
        # 2. CABANG KUALITAS (DENSE LAYER / MLP)
        # ---------------------------------------------------
        # Input: 1 nilai (Skor Kualitas 0-1)
        # Output: Vektor representasi kualitas (misal: 16 dimensi)
        self.quality_mlp = nn.Sequential(
            nn.Linear(1, 16),
            nn.GELU(), # GELU seringkali lebih baik dari ReLU di arsitektur Transformer
            nn.Linear(16, 16),
            nn.GELU()
        )

        # ---------------------------------------------------
        # 3. FUSION & FULLY CONNECTED CLASSIFIER
        # ---------------------------------------------------
        # Input: 1024 (Visual) + 16 (Quality) = 1040 dimensi
        self.classifier = nn.Sequential(
            nn.Linear(swin_out_features + 16, 512),
            nn.GELU(),
            nn.Dropout(0.3), # Mencegah overfitting
            nn.Linear(512, num_classes) # Output: 2 node (GON- dan GON+)
        )

    def forward(self, image, quality_score):
        # A. Ekstraksi Fitur Spasial
        visual_features = self.swin(image) # Shape: [Batch, 1024]

        # B. Ekstraksi Fitur Kualitas
        # Pastikan skor kualitas punya dimensi [Batch, 1] bukan cuma [Batch]
        if quality_score.dim() == 1:
            quality_score = quality_score.unsqueeze(1)

        quality_features = self.quality_mlp(quality_score) # Shape: [Batch, 16]

        # C. Fusion / Concatenation
        # Menggabungkan kedua vektor secara horizontal (dim=1)
        fused_features = torch.cat((visual_features, quality_features), dim=1) # Shape: [Batch, 1040]

        # D. Prediksi Akhir
        output = self.classifier(fused_features) # Shape: [Batch, 2]

        return output

# ======================================================
# UJI COBA ARSITEKTUR (SIMULASI FORWARD PASS)
# ======================================================
if __name__ == "__main__":
    print("--- Inisialisasi Model Quality-Aware Swin ---")
    # Gunakan versi 'tiny' atau 'small' dulu jika memori GPU terbatas,
    # tapi kita pakai 'base' sesuai standar umum
    model = QualityAwareSwin(model_name='swin_base_patch4_window7_224', pretrained=True)

    # Ambil 1 batch dari train_loader (Tahap 2) yang sudah kita buat sebelumnya
    # Jika train_loader belum jalan, kita pakai tensor dummy untuk tes:
    print("\nMembuat Tensor Dummy untuk simulasi Batch Size = 4...")
    dummy_images = torch.randn(4, 3, 224, 224) # 4 gambar RGB 224x224
    dummy_qualities = torch.tensor([0.8, 0.5, 0.9, 0.3]) # 4 skor kualitas (0-1)

    # Jalankan model
    outputs = model(dummy_images, dummy_qualities)

    print("\n✅ TAHAP 3 SELESAI: Forward Pass Berhasil!")
    print(f"Shape Output: {outputs.shape}") # Harus [4, 2] (4 batch, 2 kelas)
    print(f"Hasil Logit Prediksi:\n{outputs}")

# ======================================================
# 1. IMPLEMENTASI FOCAL LOSS (Mengatasi Imbalance)
# ======================================================
class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        """
        Focal Loss menekan nilai loss untuk contoh yang mudah ditebak (mayoritas)
        dan memaksa model fokus pada contoh yang sulit (minoritas GON-).
        """
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.reduction = reduction
        # Alpha digunakan untuk memberikan bobot ekstra pada kelas minoritas
        if alpha is not None:
            self.alpha = torch.tensor(alpha, dtype=torch.float32)
        else:
            self.alpha = None

    def forward(self, inputs, targets):
        # Hitung standard Cross Entropy Loss
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')

        # pt adalah probabilitas prediksi dari kelas yang benar
        pt = torch.exp(-ce_loss)

        # Terapkan faktor pemfokus (1 - pt)^gamma
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss

        if self.alpha is not None:
            alpha_t = self.alpha.to(inputs.device)[targets]
            focal_loss = alpha_t * focal_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        else:
            return focal_loss.sum()

# ======================================================
# 2. SETUP TRAINING LOOP & OPTIMISASI
# ======================================================
def train_model(model, train_loader, val_loader, num_epochs=5):
    # Pindahkan model ke GPU jika tersedia
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    print(f"--- Memulai Pelatihan menggunakan device: {device} ---")

    # Inisialisasi Focal Loss
    # Karena GON- (kelas 0) adalah minoritas 27%, kita beri bobot lebih tinggi (misal 0.73)
    # GON+ (kelas 1) adalah mayoritas 73%, kita beri bobot lebih rendah (misal 0.27)
    criterion = FocalLoss(alpha=[0.73, 0.27], gamma=2.0)

    # Optimizer AdamW (Varian Adam dengan Weight Decay yang lebih baik untuk Transformer)
    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)

    # Loop Pelatihan per Epoch
    for epoch in range(num_epochs):
        model.train() # Mode training (mengaktifkan Dropout & Gradient Tracking)
        running_loss = 0.0
        correct_preds = 0
        total_preds = 0

        print(f"\nEpoch {epoch+1}/{num_epochs}")
        # Progress bar menggunakan tqdm
        progress_bar = tqdm(train_loader, desc="Training", leave=False)

        for batch in progress_bar:
            # Pindahkan data ke GPU
            images = batch['image'].to(device)
            qualities = batch['quality'].to(device)
            labels = batch['label'].to(device)

            # 1. Zero Grad (Bersihkan sisa gradien dari iterasi sebelumnya)
            optimizer.zero_grad()

            # 2. Forward Pass (Prediksi)
            outputs = model(images, qualities)

            # 3. Hitung Focal Loss
            loss = criterion(outputs, labels)

            # 4. Backpropagation (Menghitung arah turunan/gradien)
            loss.backward()

            # 5. Optimization Step (Update bobot model bergerak menuju titik minimum loss)
            optimizer.step()

            # --- Perhitungan Metrik Akurasi Sederhana ---
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total_preds += labels.size(0)
            correct_preds += (predicted == labels).sum().item()

            progress_bar.set_postfix(loss=loss.item(), acc=(correct_preds/total_preds)*100)

        epoch_loss = running_loss / len(train_loader)
        epoch_acc = (correct_preds / total_preds) * 100
        print(f"Train Loss: {epoch_loss:.4f} | Train Acc: {epoch_acc:.2f}%")

        # --- (Opsional di sini: Tambahkan Validation Loop) ---

# ======================================================
# 3. EKSEKUSI TRAINING
# ======================================================
if __name__ == "__main__":
    # Asumsi model, train_loader, val_loader sudah ada di memory (dari Tahap 2 & 3)
    # Kita jalankan simulasi 1 epoch saja dulu untuk memastikan pipeline tidak error
    try:
        train_model(model, train_loader, val_loader, num_epochs=1)
        print("\n✅ TAHAP 4 SELESAI: Model berhasil melakukan Backpropagation dan Update Bobot!")
    except Exception as e:
        print(f"❌ Terjadi Error saat training: {e}")

def evaluate_metrics(model, dataloader, device):
    print("--- Memulai Evaluasi Model ---")
    model.eval() # Penting: Matikan Dropout dan BatchNorm agar hasil konsisten

    all_labels = []
    all_preds = []
    all_probs = []

    # Matikan pelacakan gradien (menghemat memori dan mempercepat proses)
    with torch.no_grad():
        for batch in dataloader:
            images = batch['image'].to(device)
            qualities = batch['quality'].to(device)
            labels = batch['label'].to(device)

            # Forward pass
            outputs = model(images, qualities)

            # Hitung probabilitas menggunakan Softmax untuk kelas 1 (GON+)
            probs = torch.softmax(outputs, dim=1)[:, 1]
            # Ambil kelas dengan nilai logit tertinggi
            _, preds = torch.max(outputs, 1)

            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    # Hitung Metrik
    f1 = f1_score(all_labels, all_preds)
    auroc = roc_auc_score(all_labels, all_probs)
    cm = confusion_matrix(all_labels, all_preds)

    print(f"\n✅ Hasil Evaluasi:")
    print(f"F1-Score : {f1:.4f}")
    print(f"AUROC    : {auroc:.4f}")
    print("\nClassification Report:")
    print(classification_report(all_labels, all_preds, target_names=['GON-', 'GON+']))

    # Visualisasi Confusion Matrix
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['GON-', 'GON+'], yticklabels=['GON-', 'GON+'])
    plt.title('Confusion Matrix')
    plt.ylabel('Label Sebenarnya')
    plt.xlabel('Prediksi Model')
    plt.show()

# Cara menjalankan:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
evaluate_metrics(model, val_loader, device)